debug_data_dir: "result/vive-calib-data-many"
device_id: 2
board_width: 10
board_height: 7
img_width: 1920
img_height: 1080
fps: 5
pattern_size_mm: 30.0
board_pattern: "chessboard"
cam_model: "pinhole"
image_width: 1920
image_height: 1080
square_size_mm: 15.0 #115.7 #30.88 #115.70
balance: 0.0
checkerboard_images_dir: "2024-08-19_07-04-19"
show_debug: false
calib_xml_name: "broad_calib.xml"
